# Generated by Django 4.2.6 on 2023-10-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('requestor', 'Requestor'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
